---
title: "proof-of-concept"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{proof-of-concept}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r setup}
library(ggplot2)
library(edibble)
library(deggust)

set.seed(1231) 

rcbd <- start_design(name = "RCBD") %>%
  set_units(block = c("B1", "B2"),
            unit = nested_in(block, 6)) %>%
  set_trts(trt = LETTERS[1:4]) %>%
  allocate_trts(~unit) %>%
  randomise_trts() %>% 
  serve_table()
```
## Proof of concepts

Something like below should be the result of `autoplot(df)` with units fixed
as nesting labels. 

```{r}
grcbd <- ggplot(rcbd, aes(unit, block, fill = trt)) +
  geom_tile(color = "black", size = 1.3) +
  coord_equal()

grcbd
```

Below modifies from the "square tile" to the image provided by the user. 

```{r, eval = FALSE}
grcbd + geom_units(aes(unit), image = "person.png")
```
```{r}

```

```{r}
library(ggraph)
library(igraph)
graph <- make_empty_graph(n = 0) %>% 
  add_vertices(nv = nrow(rcbd),
               attr = rcbd)

ggraph(graph, layout = "manual",
            x = rep(1:2, each = nrow(rcbd) / 2),
            y = rep(1:(nrow(rcbd)/2), 2)) + 
  #geom_node_circle(aes(r = 0.1), fill = "red") +
  geom_node_point(aes(color = trt), size = 3) + 
  #geom_node_tile(aes(width = 1, height = 1, fill = trt)) + 
  geom_node_text(aes(label = unit)) + 
  coord_equal() + 
  xlim(0.5, 2.5)
```


```{r}
crd <- start_design() %>%
	set_trts(trt  = c("A", "B", "C")) %>%
	set_units(unit = 6) %>%
	allocate_trts(trt ~ unit) %>% 
	randomise_trts() %>% 
	serve_table() 


rcbd <- start_design() %>%
	set_trts(fertilizer  = c("A", "B", "C")) %>%
	set_units(block = 2, 
	             plant = nested_in(block, 3)) %>%
	allocate_trts(fertilizer ~ plant) %>% 
	randomise_trts() %>% 
  serve_table()

split <- start_design() %>%
	set_trts(fertilizer  = c("A", "B", "C"),
	             variety = c("a", "b")) %>%
	set_units(mainplot = 6, 
				    subplot = nested_in(mainplot, 2)) %>%
	allocate_trts(fertilizer ~ mainplot,
	                    variety ~ subplot) %>% 
	randomise_trts() %>% 
  serve_table()


```

```{r}
unit_vec <- crd[["unit"]]
edges <- data.frame(from = unit_vec[-1],
                    to = unit_vec[-length(unit_vec)])
nodes <- crd[c("unit", "trt")]
graph <- igraph::graph_from_data_frame(edges,
                                       vertices = edibble:::as_data_frame(nodes))

g1 <- ggraph::ggraph(graph,
             layout = "manual",
             x = rep(1:3, length.out = 6),
             y = sort(rep(1:2, length.out = 6))) +
ggraph::geom_edge_diagonal() +
# assumes one trt only
ggraph::geom_node_circle(ggplot2::aes(r = 0.35, fill = trt)) +
ggraph::geom_node_text(aes(label =  unit_vec), size = 7) +
ggplot2::coord_equal() +
  colorspace::scale_color_discrete_qualitative() +
  ggtitle("autoplot(crd)") +
  theme(title = element_text(size = 18, family = "Fira Code"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 16))

ggsave("~/Downloads/ggcrd.pdf", g1, width = 4, height = 2.5, device=cairo_pdf)
```



```{r}
unit_vec <- rcbd[["plant"]]
edges <- data.frame(from = unit_vec[-1],
                    to = unit_vec[-length(unit_vec)])
nodes <- rcbd[c("plant", "block", "fertilizer")]
graph <- igraph::graph_from_data_frame(edges,
                                       vertices = edibble:::as_data_frame(nodes))

g2 <- ggraph::ggraph(graph,
             layout = "manual",
             x = rep(1:3, length.out = 6),
             y = sort(rep(1:2, length.out = 6))) +
  geom_rect(data = data.frame(xmin = c(0.5, 0.5),
                              xmax = c(3.5, 3.5),
                              ymin = c(0.6, 1.6),
                              ymax = c(1.4, 2.4),
                              block = c("block1", "block2")),
            aes(xmin = xmin, xmax = xmax, 
                ymin = ymin, ymax = ymax,
                fill = block),
            alpha = 0.6, color = "black") +
  ggnewscale::new_scale_fill() +
ggraph::geom_edge_diagonal() +
# assumes one trt only
ggraph::geom_node_circle(ggplot2::aes(r = 0.35, fill = fertilizer)) +
ggraph::geom_node_text(aes(label =  unit_vec), size = 7) +
ggplot2::coord_equal() +
  colorspace::scale_color_discrete_qualitative() +
  ggtitle("autoplot(rcbd)") +
  theme(title = element_text(size = 18, family = "Fira Code"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 16))

g2

ggsave("~/Downloads/ggrcbd.pdf", g2, width = 6, height = 3, device=cairo_pdf)
```


```{r}
split2 <- split %>% 
  dplyr::mutate(subplot = gsub("subplot", "sub\nplot", subplot))
unit_vec <- split2[["subplot"]]
edges <- data.frame(from = unit_vec[-1],
                    to = unit_vec[-length(unit_vec)])
nodes <- split2[c("subplot", "mainplot", "variety", "fertilizer")] 
graph <- igraph::graph_from_data_frame(edges,
                                       vertices = edibble:::as_data_frame(nodes))

g3 <- ggraph::ggraph(graph,
             layout = "manual",
             x = rep(1:4, length.out = 12),
             y = sort(rep(c(1, 2.25, 3.5), length.out = 12))) +
  ggforce::geom_ellipse(data = data.frame(
    x0 = c(1.5, 3.5, 1.5, 3.5, 1.5, 3.5),
    y0 = c(1, 1, 2.25, 2.25, 3.5, 3.5),
    fertilizer = split[["fertilizer"]][rep(c(TRUE, FALSE), length.out = 12)]),
                        aes(x0 = x0, y0 = y0, fill = fertilizer,
                            a = 0.95, b = 0.6, angle = 0),
    color = "black", alpha = 0.4) + 
  # geom_rect(data = data.frame(xmin = c(0.6, 0.6, 0.6, 2.6, 2.6, 2.6),
  #                             xmax = c(2.4, 2.4, 2.4, 4.4, 4.4, 4.4),
  #                             ymin = c(0.6, 1.6, 2.6, 0.6, 1.6, 2.6),
  #                             ymax = c(1.4, 2.4, 3.4, 1.4, 2.4, 3.4),
  #                             fertilizer = split[["fertilizer"]][rep(c(TRUE, FALSE), length.out = 12)][c(1, 3, 5, 2, 4, 6)]),
  #           aes(xmin = xmin, xmax = xmax, 
  #               ymin = ymin, ymax = ymax,
  #               fill = fertilizer),
  #           alpha = 0.4, color = "black") +
  ggnewscale::new_scale_fill() +
ggraph::geom_edge_diagonal() +
# assumes one trt only
ggraph::geom_node_circle(ggplot2::aes(r = 0.35, fill = variety)) +
ggraph::geom_node_text(aes(label =  unit_vec), size = 4, lineheight = .7) +
ggplot2::coord_equal() +
  colorspace::scale_color_discrete_qualitative() +
  ggtitle("autoplot(split)") +
  theme(title = element_text(size = 18, family = "Fira Code"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 16))



ggsave("~/Downloads/ggsplit.pdf", g3, width = 6, height = 4, device=cairo_pdf)
```
